#pragma once

#define MAX_PATH 260
#define WM_USER 0x0400
#define WM_USER_MSG WM_USER + 102

typedef enum _USER_MSG
{
	MSG_PARTITION = 1,
	MSG_FAT32_ITEM,
	MSG_NTFS_ITEM,

	MSG_UPDATE_PROGRESS,
	MSG_UPDATE_STATUS,

	MSG_DONE_INITIALIZE_PARTITION,
	MSG_DONE_SCAN_PARTITION,
	MSG_DONE_RECOVER,
	MSG_DONE_DEEPSCAN_PARTITION,
}USER_MSG;

typedef enum _SCAN_MODE
{	
	MODE_NORMAL = 1,
	MODE_RESTORE,
	MODE_INTELLECT,
}SCAN_MODE;

typedef enum _TASK_TOKEN
{
	TASK_READ_PARTITION = 1,
	TASK_ANALYSIS_PARTITION,
	TASK_RECOVER_FILE,
	TASK_DEEPSCAN,
}TASK_TOKEN;

typedef enum _PARTITION_TYPE
{
	FS_UNKNOWN = 0,
	FS_NTFS = 1,
	FS_FAT32 = 2,
}PARTITION_TYPE;

typedef struct _PARTITION_ITEM
{
	HANDLE DeviceHandle;
	ULONGLONG StartSector;
	ULONGLONG SectorCount;
	PARTITION_TYPE PartitionType;
	TCHAR* Volume;
}PARTITION_ITEM, *PPARTITION_ITEM;

typedef struct _FAT32_ITEM
{
	ULONGLONG Sector;
	ULONGLONG Size;
	BOOL IsDeleted;
	TCHAR CreateDate[20];
	TCHAR* Name;
}FAT32_ITEM, *PFAT32_ITEM;

typedef struct _NTFS_ITEM
{
	ULONG FileReferenceNumber;
	ULONGLONG Size;
	BOOL IsDeleted;
	TCHAR CreateDate[20];
	TCHAR* Name;
}NTFS_ITEM, *PNTFS_ITEM;